### ISSUE TITLE
QnToolsSimulationTests: /usr/bin/ld: cannot find -lROOTVecOps

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#18]
This issue appeared today after pulling from master. It appears while **QnToolsSimulationTests** is being built.

> $ root-config --version
> 6.20/04
> $ root-config --features
> cxx17 asimage builtin_clang builtin_llvm builtin_vdt clad dataframe exceptions fftw3 fitsio gdml http mathmore mlp pyroot roofit webgui root7 runtime_cxxmodules shared ssl tmva tmva-pymva spectrum vdt x11

Removing ROOTVecOps from dependencies list fixes the problem. This is weird, because libROOTVecOps.so exists in the system.

I propose:

- Remove ROOTVecOps from QnToolsSimulationTests (or make it optional)
- Set building of QnToolsSimulationTests optional

**Comment by kreisl** [comment]
Yeah I see the same bug. I don't know why this is somehow the linker doesn't find the vecops... I fixed it exactly the same way. I will push some additional changes to the target_link_libraries because of additional bugs with aliphysics.

**Comment by kreisl** [comment]
see pull request #21
