### ISSUE TITLE
Proposal: remove static polymorphism of CorrectionManager::AddDetector

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#19]
Currently CorrectionManager::AddDetector has integer template parameter _N_ which defines size of raw C++ array for the list of needed harmonics in the argument of AddDetector.

Despite we rarely change this parameter, static-ness of AddDetector conceptually blocks any possibility for complete runtime configuration of correction task.

**Comment by kreisl** [comment]
I think this is a leftover from the old framework. This should be changable without too much impact on other stuff.
