### ISSUE TITLE
QnTools with old ROOT

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#31]
Hi!

Colleagues reported that QnTools requires minimum 6/20 version of ROOT:
https://github.com/HeavyIonAnalysis/QnTools/blob/defca4cc9f7876e854f1af5f7c622255dbc4b508/CMakeLists.txt#L40

I'm fully supporting the idea to not care about compatibility with really old software but ROOT 6/18 is not that old in my opinion. For example at the moment CBM is providing `root-6.16.00-gcc-8.1.0-nrkpihv`.

**Comment by kreisl** [comment]
I think it should work with 6.18. You could try to edit the line 
https://github.com/HeavyIonAnalysis/QnTools/blob/defca4cc9f7876e854f1af5f7c622255dbc4b508/CMakeLists.txt#L40 I am not 100% sure it works. But I don't remember any breaking changes. Maybe the dataframe part might not perform as well? Does anyone have a testing environment for 6.18? ALICE already provides 6.20 and my local root is also min. version 6.20.

**Comment by kreisl** [comment]
I would suggest as soon as we know it works we can push the version down to either 6.16 or 6.18.

**Comment by eugene274** [comment]
I checked with ROOT v6.16.
It builds.
