### ISSUE TITLE
New correlation weights management

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#39]
Hi!

I've recently found that you refactored management of weights for correlation task. So now I have to pass two functions one for correlation itself and another one which evaluates weights.

I have few questions concerning underlying math. 
Previously we had OBSERVABLE type and REFERENCE type of Q-vectors. Is there a representation of those types in new version?
You added weights functions into `CorrelationFunctions.hpp`. Maybe I'm stupid, but I cannot catch new notation (`n2`, `nd2`,etc). Can you clarify this? I see also that there is a common ansatz for weights of the form `M(M-1)`. Can you also say few words on that?

Thanks a lot!

**Comment by kreisl** [comment]
The observable and reference type are still there now it is named use_weights_. If use_weights_ is true the resulting correlation will be of type OBSERVABLE.
We now need to pass a second function which takes care of the weights. There are some premade ones for the cumulant methods. 
For example:
v_2{2} = sqrt(c_2{2})
c_2{2} = <C_2> <> is event average

Edit:
In the case of my functions c2 = C_2 per event. So n2 is already divided out.
However It is still needed during the event average which is weighted by n2.
<C_2> = (sum_i^N C_2 n2) / (sum_i^N n2)

So `n2` is equivalent to the weight / multiplicity `m(m-1)` the Q-vector 
`nd2` is supposed to be the same for differential cumulants, which make the distinction between particles of interest `p` and reference particles `r`. `d2` is the corresponding numerator for differential cumulants.
it is a similar notation to: https://arxiv.org/pdf/1312.3572.pdf
Maybe we should adopt the same notation and link to this paper to make it easier to understand, what the purpose of these functions are.
