### ISSUE TITLE
Segfault on destruction of CorrectionManager

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#43]
Segfault occurs on destruction of `TFile` in CorrectionManager: 
https://github.com/HeavyIonAnalysis/QnTools/blob/edf2bed98e91d1ce479d2d21430a390c9f1338f5/include/correction/QnTools/CorrectionManager.hpp#L303

**Comment by kreisl** [comment]
Is this a problem due to the unique_ptr going out of scope? Not sure if having a TFile as a unique_ptr is recommended in root.

**Comment by eugene274** [comment]
The problem was in out project.
Never forget virtual destructors.
