### ISSUE TITLE
AverageHelper: crash during Finalize

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#45]
I'm getting out of range error at this line:
https://github.com/HeavyIonAnalysis/QnTools/blob/f39fe1fd34d9b01037e28e369a25c9fe03f0b4e4/src/dataframe/common/AverageHelper.hpp#L174

Both `results_` and `is_configured_` have 1 element and `is_configure_[0] = false`.
In this situation iterator
https://github.com/HeavyIonAnalysis/QnTools/blob/f39fe1fd34d9b01037e28e369a25c9fe03f0b4e4/src/dataframe/common/AverageHelper.hpp#L171
points to `is_configured_.end()`. And it gives out of range index for `results_`.

I don't know whether this is healthy situation or not.

UPD. This is happening when `tree->GetEntries() == 0`

**Comment by kreisl** [comment]
Does this case affect regular usage? I can have a look at this on Monday, or do you have an idea how to fix this problem? I am not sure how the data frame initialized the helper, if the tree has 0 entries.

**Comment by eugene274** [comment]
I think, it is enough to check if none of slots are initialized. And if yes, throw runtime error with understandable message.

**Comment by eugene274** [comment]
I think this has been solved
