### ISSUE TITLE
QnTools - correction logic

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#46]
Hi Lukas,

I'm trying to run flow analysis for our data in NA61/Shine. I'm seeing now weird difference between 'x' and 'y' component (not seen before), so I decided to look into correction step to understand what is going on.

There is a Q-vector `pion_neg_pt` which is related to negative pions. Corrections: RECENTERING, TWIST-AND-RESCALE.  Normalization: sum of weights. Weight: Ones.

I'm looking at single kinematic bin, only events where number of contributing vectors == 1. So, it is data_[0] and data_[0].n_ == 1

**PLAIN:**  First harmonic x and y
![xVsY_PLAIN_n1](https://user-images.githubusercontent.com/23106384/102460301-d8e2b280-4057-11eb-82aa-768eb03de45b.png)

Circle is expected, circle is found. Non-uniform acceptance of the NA61 is clearly seen here.

Same plot, but now **RECENTERED**:

![xVsY_RECENTERED_n1](https://user-images.githubusercontent.com/23106384/102461045-e2b8e580-4058-11eb-9f05-931b280d550c.png)

I expected to see one circle (since it is only one kinematical bin) with shifted centre. But here centre is fluctuating (event-by-event).

Can you clarify this?

**Comment by eugene274** [comment]
I forgot about event axes.

**Comment by eugene274** [comment]
Still there is a question on performance of the correction. I'm plotting ATan2 to check out uniformity of Phi distributions after all corrections:

**PLAIN:**
![ATan2_PLAIN_n1](https://user-images.githubusercontent.com/23106384/102463224-e26e1980-405b-11eb-9975-22822491edb7.png)
**RECENTERED:**
![ATan2_RECENTERED_n1](https://user-images.githubusercontent.com/23106384/102463425-219c6a80-405c-11eb-8bc3-baab56aa8f29.png)
**TWIST:**
![ATan2_TWIST_n1](https://user-images.githubusercontent.com/23106384/102463523-4690dd80-405c-11eb-9992-15a70f55eed4.png)
**RESCALING:**
![xVsY_RESCALING_n1](https://user-images.githubusercontent.com/23106384/102463621-66c09c80-405c-11eb-8d60-cb20f381b17c.png)

As you can see, `RESCALING` significantly increases the non-uniformity. 
Actually, it looks a bit unhealthy.

**Comment by eugene274** [comment]
Weighted values with number of vectors participating in Q

![ATan2_RESCALED_wn](https://user-images.githubusercontent.com/23106384/102465520-cb7cf680-405e-11eb-8e5e-a45d6fb2a546.png)

**Comment by kreisl** [comment]
We should check with a toy MC if those effects are also seen there. This is also still on the todo for the Framework to include such checks.

**Comment by eugene274** [comment]
Hi again!

>I'm trying to run flow analysis for our data in NA61/Shine. I'm seeing now weird difference between 'x' and 'y' component (not seen before), so I decided to look into correction step to understand what is going on.

This is not actual anymore. I used last version (with PR #44) and the problem has gone.

**Comment by kreisl** [comment]
Is there still an issue?

**Comment by eugene274** [comment]
Not anymore
