### ISSUE TITLE
Problem with selection bins on axis with non-uniform-width binning

### ISSUE THREAD

**Issue by mam-mih-val** [HeavyIonAnalysis/QnTools#48]
Dear @kreisl,

Recently, I faced the problem while attempting to select bins on an axis with non-uniform-width binning. An example of the problem appearance you can find in my repository: 
https://github.com/mam-mih-val/qn_tools_test
Please, use the file, attached to the project.

If you try to select the 9 out of 10 initial bins on pT-axis, you see, that bin-edges are biased after the operation. Moreover, the conversion of the container with selected bins into TGraph somehow gives the third version of binning with 5 bins, not similar to the previous two. 

I Hope, you can sort it out, or explain if I'm doing something wrong

Cheers,
Mikhail

**Comment by kreisl** [comment]
Hi Mikhail,
I think ``DataContainer::Select`` doesn't really do what is expected. 
I actually replaces the current axis with the one specified in the arguments.
So to do what you want you can:

1. Get the bins of the axis. 
2. Create a new one keeping only the range you want.
3. Pass this new axis to the ``DataContainer::Select`` function.
For this to be easier I think we might need a new function.

Could you try if this fixes your problem?

Cheers,
Lukas

**Comment by kreisl** [comment]
Is this problem fixed resolved?

**Comment by eugene274** [comment]
AFAIK this was fixed in 
#49 
#53 
@mam-mih-val ?

**Comment by mam-mih-val** [comment]
Sorry for the late reply. The problem is resolved. Thank you!
