### ISSUE TITLE
Deprecation of TROOT::GetImplicitMTPoolSize

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#57]
With root v6.22 I'm getting warning:

```
In file included from /home/eugene/CLionProjects/QnAnalysis/cmake-build-debug/_deps/qntools-src/src/dataframe/common/AverageHelper.hpp:28,
                 from /home/eugene/CLionProjects/QnAnalysis/cmake-build-debug/_deps/qntools-src/src/dataframe/QnDataFrame.hpp:20,
                 from /home/eugene/CLionProjects/QnAnalysis/src/QnAnalysisCorrelate/CorrelationTaskRunner.hpp:22,
                 from /home/eugene/CLionProjects/QnAnalysis/src/QnAnalysisCorrelate/CorrelationTaskRunner.cpp:8:
/home/eugene/SOFT/ROOT/root-6.22.02.gcc10.1/include/TROOT.h:89:11: note: declared here
   89 |    UInt_t GetImplicitMTPoolSize() R__DEPRECATED(6, 24, "Please use ROOT::GetThreadPoolSize() instead");
```

**Comment by eugene274** [comment]
master: GetImplicitMTPoolSize() fallbacks to GetThreadPoolSize()
6.24: GetImplicitMTPoolSize() fallbacks to GetThreadPoolSize()
6.22: GetImplicitMTPoolSize() fallbacks to GetThreadPoolSize()
6.20: GetImplicitMTPoolSize()
6.18: GetImplicitMTPoolSize()

**Comment by kreisl** [comment]
Do you propose a macro which detects the root version?
Do we need the backwards compatibility to 6.20?

**Comment by eugene274** [comment]
> Do you propose a macro which detects the root version?

Yep.  I'm working on it.

> Do we need the backwards compatibility to 6.20?

I believe if we can support that, why not to?
