### ISSUE TITLE
Improper use of the std::array::empty

### ISSUE THREAD

**Issue by eugene274** [HeavyIonAnalysis/QnTools#62]
https://github.com/HeavyIonAnalysis/QnTools/blob/f0e2818ce5b10254bcf4985821d86599e3903783/src/dataframe/correlation/CorrelationAction.hpp#L234

This leads to weird "no such branch" errors in runtime due to uninitialized array;

**Comment by kreisl** [comment]
defined as vector here:
https://github.com/HeavyIonAnalysis/QnTools/blob/f0e2818ce5b10254bcf4985821d86599e3903783/src/dataframe/correlation/CorrelationAction.hpp#L74-L75

redefined as array here:
https://github.com/HeavyIonAnalysis/QnTools/blob/f0e2818ce5b10254bcf4985821d86599e3903783/src/dataframe/correlation/CorrelationAction.hpp#L143-L144

It doesn't look like it is on purpose.
