### ISSUE TITLE
Weights constraint

### ISSUE THREAD

**Issue by lubynets** [HeavyIonAnalysis/QnTools#9]
Dear all,

In src/dataframe/correlation/CorrelationAction.hpp there is a specific condition in LoopOverBins() function (lines 314 and 325):
if sum of weights is smaller than 1, this entry is not added to correlations.

I wonder if this condition is necessary. And what about case of magnitude normalization, when we can operate with weights smaller than 1?

**Comment by kreisl** [comment]
No, thanks for spotting it. It should be number of data vectors `n()` instead of `sumofweights()`

**Comment by kreisl** [comment]
fixed in pull request #10
